name: Broken Links Check

on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Broken-Links-Crawler
        uses: ScholliYT/Broken-Links-Crawler-Action@v3.3.2
        with:
          website_url: "https://locinet.github.io/locinet"
          verbose: 'true'
